stages:
  - build
  - test
  - deploy

variables:
  DEPLOY_USER: "nyism"
  DEPLOY_SERVER: "your_vm_ip"
  DEPLOY_PATH: "C:\Users\nlahri\OneDrive - NEVERHACK\Documents\GitHub\NyismProject"
  DEPLOY_SSH_KEY: "/path/to/your/private-key.pem"

before_script:
  - apt-get update -y
  - apt-get install -y sshpass

build:
  stage: build
  script:
    - echo "Building the Python application..."
    - pip install -r
